# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1dfa931ecaa2a12b774c5a828561db85915da3a5582940a4a61edd076cb3321750edfb1471268fcd4384edc6553201d67f5956f683b1049841b85a61a503e1c

test:
  secret_key_base: 3f23efb17bd7b87d2aaed9bb9f444f7b32fcd10c66a16338798d008a80aea750428be2bd8537d7412ee4239c6b1716cb8e57f46114024bd0568b732a5561bef8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
